package com.myhealth.domain.engine.strength

import com.myhealth.domain.model.Equipment as Eq
import com.myhealth.domain.model.Exercise
import com.myhealth.domain.model.MovementPattern as P
import com.myhealth.domain.model.MuscleGroup as M

/**
 * The lower-body half of the catalog (PLAN §3.12.1) — squat, hinge, lunge, the machine isolations
 * and the two plyometric/hold entries. Split out of [ExerciseCatalog] for R10 only; the list is
 * data, and [ExerciseCatalog.ALL] is the single place that concatenates the three files.
 *
 * `primary` and `secondary` are always disjoint (`ex03`) — a group that is genuinely doing the
 * work is primary and never repeated as an assistant.
 */
internal val LOWER_BODY_EXERCISES: List<Exercise> = listOf(
    Exercise(
        id = "BARBELL_BACK_SQUAT",
        name = "Barbell back squat",
        primary = setOf(M.QUADS, M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.LOWER_BACK, M.ABS),
        equipment = Eq.BARBELL,
        pattern = P.SQUAT,
        cue = "Brace hard, sit down between the hips, knees tracking over the toes.",
    ),
    Exercise(
        id = "FRONT_SQUAT",
        name = "Front squat",
        primary = setOf(M.QUADS),
        secondary = setOf(M.GLUTES, M.ABS, M.LOWER_BACK),
        equipment = Eq.BARBELL,
        pattern = P.SQUAT,
        cue = "Elbows high, upright torso; the bar stays over mid-foot.",
    ),
    Exercise(
        id = "GOBLET_SQUAT",
        name = "Goblet squat",
        primary = setOf(M.QUADS),
        secondary = setOf(M.GLUTES, M.ABS),
        equipment = Eq.DUMBBELL,
        pattern = P.SQUAT,
        cue = "Hold the bell at the chest, elbows inside the knees at the bottom.",
    ),
    Exercise(
        id = "LEG_PRESS",
        name = "Leg press",
        primary = setOf(M.QUADS, M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.CALVES),
        equipment = Eq.MACHINE,
        pattern = P.SQUAT,
        cue = "Feet shoulder-width, stop before the lower back rounds off the pad.",
    ),
    Exercise(
        id = "WALL_SIT",
        name = "Wall sit",
        primary = setOf(M.QUADS),
        secondary = setOf(M.GLUTES, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.SQUAT,
        isTimed = true,
        cue = "Thighs parallel, back flat on the wall, breathe through the burn.",
    ),
    Exercise(
        id = "CONVENTIONAL_DEADLIFT",
        name = "Conventional deadlift",
        primary = setOf(M.GLUTES, M.HAMSTRINGS, M.LOWER_BACK),
        secondary = setOf(M.QUADS, M.TRAPS, M.LATS, M.FOREARMS),
        equipment = Eq.BARBELL,
        pattern = P.HINGE,
        cue = "Bar against the shins, lats tight, push the floor away.",
    ),
    Exercise(
        id = "ROMANIAN_DEADLIFT",
        name = "Romanian deadlift",
        primary = setOf(M.HAMSTRINGS, M.GLUTES),
        secondary = setOf(M.LOWER_BACK, M.FOREARMS),
        equipment = Eq.BARBELL,
        pattern = P.HINGE,
        cue = "Soft knees, push the hips back, stop where the hamstrings run out.",
    ),
    Exercise(
        id = "SINGLE_LEG_RDL",
        name = "Single-leg Romanian deadlift",
        primary = setOf(M.HAMSTRINGS, M.GLUTES),
        secondary = setOf(M.LOWER_BACK, M.ABS, M.CALVES),
        equipment = Eq.DUMBBELL,
        pattern = P.HINGE,
        unilateral = true,
        cue = "Hips square, back leg in line with the spine, slow on the way down.",
    ),
    Exercise(
        id = "HIP_THRUST",
        name = "Barbell hip thrust",
        primary = setOf(M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.ABS),
        equipment = Eq.BARBELL,
        pattern = P.HINGE,
        cue = "Ribs down, chin tucked, finish with the shins vertical.",
    ),
    Exercise(
        id = "GLUTE_BRIDGE",
        name = "Glute bridge",
        primary = setOf(M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.HINGE,
        cue = "Heels close to the hips, squeeze at the top for a full second.",
    ),
    Exercise(
        id = "KETTLEBELL_SWING",
        name = "Kettlebell swing",
        primary = setOf(M.GLUTES, M.HAMSTRINGS),
        secondary = setOf(M.LOWER_BACK, M.ABS, M.SHOULDERS_FRONT),
        equipment = Eq.KETTLEBELL,
        pattern = P.HINGE,
        cue = "A hinge, not a squat — the bell floats, the hips snap.",
    ),
    Exercise(
        id = "WALKING_LUNGE",
        name = "Walking lunge",
        primary = setOf(M.QUADS, M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.ADDUCTORS, M.CALVES),
        equipment = Eq.DUMBBELL,
        pattern = P.LUNGE,
        unilateral = true,
        cue = "Long step, upright torso, knee to a whisper off the floor.",
    ),
    Exercise(
        id = "REVERSE_LUNGE",
        name = "Reverse lunge",
        primary = setOf(M.GLUTES, M.QUADS),
        secondary = setOf(M.HAMSTRINGS, M.ADDUCTORS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.LUNGE,
        unilateral = true,
        cue = "Step back, weight on the front heel; kinder on the knee than a forward lunge.",
    ),
    Exercise(
        id = "BULGARIAN_SPLIT_SQUAT",
        name = "Bulgarian split squat",
        primary = setOf(M.QUADS, M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.ADDUCTORS, M.ABS),
        equipment = Eq.DUMBBELL,
        pattern = P.LUNGE,
        unilateral = true,
        cue = "Rear foot on the bench, front shin near vertical, hips down not forward.",
    ),
    Exercise(
        id = "STEP_UP",
        name = "Step-up",
        primary = setOf(M.QUADS, M.GLUTES),
        secondary = setOf(M.HAMSTRINGS, M.CALVES),
        equipment = Eq.DUMBBELL,
        pattern = P.LUNGE,
        unilateral = true,
        cue = "Drive through the top foot; do not push off the trailing leg.",
    ),
    Exercise(
        id = "LEG_CURL",
        name = "Lying leg curl",
        primary = setOf(M.HAMSTRINGS),
        secondary = setOf(M.CALVES),
        equipment = Eq.MACHINE,
        pattern = P.ISOLATION,
        cue = "Hips pinned to the pad, three seconds back down.",
    ),
    Exercise(
        id = "LEG_EXTENSION",
        name = "Leg extension",
        primary = setOf(M.QUADS),
        equipment = Eq.MACHINE,
        pattern = P.ISOLATION,
        cue = "Pause at the top, control the eccentric; no swinging the seat.",
    ),
    Exercise(
        id = "NORDIC_HAMSTRING_CURL",
        name = "Nordic hamstring curl",
        primary = setOf(M.HAMSTRINGS),
        secondary = setOf(M.GLUTES, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.ISOLATION,
        cue = "Hips extended, lower as slowly as you can, catch with the hands.",
    ),
    Exercise(
        id = "HIP_ABDUCTION",
        name = "Hip abduction",
        primary = setOf(M.GLUTES),
        secondary = setOf(M.LOWER_BACK),
        equipment = Eq.MACHINE,
        pattern = P.ISOLATION,
        cue = "Lean slightly forward to bias the glute medius; open slowly.",
    ),
    Exercise(
        id = "HIP_ADDUCTION",
        name = "Hip adduction",
        primary = setOf(M.ADDUCTORS),
        secondary = setOf(M.GLUTES),
        equipment = Eq.MACHINE,
        pattern = P.ISOLATION,
        cue = "Full range in, no bouncing out — the groin is a running injury waiting to happen.",
    ),
    Exercise(
        id = "CALF_RAISE",
        name = "Standing calf raise",
        primary = setOf(M.CALVES),
        equipment = Eq.BODYWEIGHT,
        pattern = P.ISOLATION,
        cue = "Full stretch at the bottom, a one-second squeeze at the top.",
    ),
    Exercise(
        id = "BOX_JUMP",
        name = "Box jump",
        primary = setOf(M.QUADS, M.GLUTES),
        secondary = setOf(M.CALVES, M.HAMSTRINGS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.PLYOMETRIC,
        cue = "Land soft and quiet, step down rather than jumping down.",
    ),
)
