package com.myhealth.domain.engine.strength

import com.myhealth.domain.model.Equipment as Eq
import com.myhealth.domain.model.Exercise
import com.myhealth.domain.model.MovementPattern as P
import com.myhealth.domain.model.MuscleGroup as M

/**
 * The upper-body half of the catalog (PLAN §3.12.1): the four push/pull patterns, the arm and
 * shoulder isolations, and the two carries. Split out of [ExerciseCatalog] for R10.
 *
 * `ex05` pins the bench press exactly: primary `{CHEST}`, secondary `{TRICEPS, SHOULDERS_FRONT}`.
 */
internal val UPPER_BODY_EXERCISES: List<Exercise> = listOf(
    Exercise(
        id = "BARBELL_BENCH_PRESS",
        name = "Barbell bench press",
        primary = setOf(M.CHEST),
        secondary = setOf(M.TRICEPS, M.SHOULDERS_FRONT),
        equipment = Eq.BARBELL,
        pattern = P.HORIZONTAL_PUSH,
        cue = "Shoulder blades pinned, bar to the lower chest, elbows about 45°.",
    ),
    Exercise(
        id = "INCLINE_DUMBBELL_PRESS",
        name = "Incline dumbbell press",
        primary = setOf(M.CHEST, M.SHOULDERS_FRONT),
        secondary = setOf(M.TRICEPS),
        equipment = Eq.DUMBBELL,
        pattern = P.HORIZONTAL_PUSH,
        cue = "Bench at 30°, wrists stacked over the elbows, no clanking at the top.",
    ),
    Exercise(
        id = "PUSH_UP",
        name = "Push-up",
        primary = setOf(M.CHEST),
        secondary = setOf(M.TRICEPS, M.SHOULDERS_FRONT, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.HORIZONTAL_PUSH,
        cue = "One straight line from heel to head; the hips do not lead.",
    ),
    Exercise(
        id = "OVERHEAD_PRESS",
        name = "Overhead press",
        primary = setOf(M.SHOULDERS_FRONT),
        secondary = setOf(M.TRICEPS, M.TRAPS, M.ABS),
        equipment = Eq.BARBELL,
        pattern = P.VERTICAL_PUSH,
        cue = "Squeeze the glutes, head through at the top, bar over mid-foot.",
    ),
    Exercise(
        id = "TRICEPS_DIP",
        name = "Triceps dip",
        primary = setOf(M.TRICEPS),
        secondary = setOf(M.CHEST, M.SHOULDERS_FRONT),
        equipment = Eq.BODYWEIGHT,
        pattern = P.VERTICAL_PUSH,
        cue = "Torso upright for triceps, leaned forward for chest; stop at 90°.",
    ),
    Exercise(
        id = "BARBELL_ROW",
        name = "Barbell row",
        primary = setOf(M.LATS),
        secondary = setOf(M.BICEPS, M.TRAPS, M.SHOULDERS_REAR, M.LOWER_BACK),
        equipment = Eq.BARBELL,
        pattern = P.HORIZONTAL_PULL,
        cue = "Hinged at about 45°, bar to the navel, no heaving with the hips.",
    ),
    Exercise(
        id = "DUMBBELL_ROW",
        name = "Dumbbell row",
        primary = setOf(M.LATS),
        secondary = setOf(M.BICEPS, M.TRAPS, M.SHOULDERS_REAR),
        equipment = Eq.DUMBBELL,
        pattern = P.HORIZONTAL_PULL,
        unilateral = true,
        cue = "Pull the elbow past the ribs; the shoulder does not rotate open.",
    ),
    Exercise(
        id = "SEATED_CABLE_ROW",
        name = "Seated cable row",
        primary = setOf(M.LATS, M.TRAPS),
        secondary = setOf(M.BICEPS, M.SHOULDERS_REAR, M.LOWER_BACK),
        equipment = Eq.CABLE,
        pattern = P.HORIZONTAL_PULL,
        cue = "Chest tall, drive the elbows back, let the shoulder blades travel.",
    ),
    Exercise(
        id = "INVERTED_ROW",
        name = "Inverted row",
        primary = setOf(M.LATS),
        secondary = setOf(M.BICEPS, M.TRAPS, M.SHOULDERS_REAR, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.HORIZONTAL_PULL,
        cue = "Body rigid, chest to the bar; raise the feet to make it harder.",
    ),
    Exercise(
        id = "FACE_PULL",
        name = "Face pull",
        primary = setOf(M.SHOULDERS_REAR, M.TRAPS),
        secondary = setOf(M.BICEPS),
        equipment = Eq.CABLE,
        pattern = P.HORIZONTAL_PULL,
        cue = "Rope to the forehead, thumbs back; the shoulder-health exercise.",
    ),
    Exercise(
        id = "BAND_PULL_APART",
        name = "Band pull-apart",
        primary = setOf(M.SHOULDERS_REAR),
        secondary = setOf(M.TRAPS),
        equipment = Eq.BAND,
        pattern = P.HORIZONTAL_PULL,
        cue = "Arms straight, band to the sternum, slow back to the start.",
    ),
    Exercise(
        id = "PULL_UP",
        name = "Pull-up",
        primary = setOf(M.LATS),
        secondary = setOf(M.BICEPS, M.FOREARMS, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.VERTICAL_PULL,
        cue = "Start from a dead hang, chest to the bar, no kipping.",
    ),
    Exercise(
        id = "CHIN_UP",
        name = "Chin-up",
        primary = setOf(M.LATS, M.BICEPS),
        secondary = setOf(M.FOREARMS, M.ABS),
        equipment = Eq.BODYWEIGHT,
        pattern = P.VERTICAL_PULL,
        cue = "Underhand grip, elbows down and in; easier than the pull-up, bigger on the arms.",
    ),
    Exercise(
        id = "LAT_PULLDOWN",
        name = "Lat pulldown",
        primary = setOf(M.LATS),
        secondary = setOf(M.BICEPS, M.SHOULDERS_REAR),
        equipment = Eq.CABLE,
        pattern = P.VERTICAL_PULL,
        cue = "Slight lean back, bar to the collarbone, no leaning it down with the body.",
    ),
    Exercise(
        id = "LATERAL_RAISE",
        name = "Lateral raise",
        primary = setOf(M.SHOULDERS_FRONT),
        secondary = setOf(M.TRAPS),
        equipment = Eq.DUMBBELL,
        pattern = P.ISOLATION,
        cue = "Light weight, lead with the elbows, stop level with the shoulders.",
    ),
    Exercise(
        id = "REAR_DELT_FLY",
        name = "Rear-delt fly",
        primary = setOf(M.SHOULDERS_REAR),
        secondary = setOf(M.TRAPS),
        equipment = Eq.DUMBBELL,
        pattern = P.ISOLATION,
        cue = "Hinged over, arms wide like a bird; the traps do not shrug.",
    ),
    Exercise(
        id = "BICEPS_CURL",
        name = "Biceps curl",
        primary = setOf(M.BICEPS),
        secondary = setOf(M.FOREARMS),
        equipment = Eq.DUMBBELL,
        pattern = P.ISOLATION,
        cue = "Elbows at the ribs, no swinging; squeeze at the top.",
    ),
    Exercise(
        id = "HAMMER_CURL",
        name = "Hammer curl",
        primary = setOf(M.BICEPS, M.FOREARMS),
        equipment = Eq.DUMBBELL,
        pattern = P.ISOLATION,
        cue = "Neutral grip throughout — the brachialis and the forearm do the work.",
    ),
    Exercise(
        id = "TRICEPS_PUSHDOWN",
        name = "Triceps pushdown",
        primary = setOf(M.TRICEPS),
        equipment = Eq.CABLE,
        pattern = P.ISOLATION,
        cue = "Elbows locked at the sides, full lockout, control the way up.",
    ),
    Exercise(
        id = "SKULL_CRUSHER",
        name = "Skull crusher",
        primary = setOf(M.TRICEPS),
        secondary = setOf(M.SHOULDERS_FRONT),
        equipment = Eq.BARBELL,
        pattern = P.ISOLATION,
        cue = "Bar to the forehead, upper arms still; stop if the elbows complain.",
    ),
    Exercise(
        id = "FARMERS_CARRY",
        name = "Farmer's carry",
        primary = setOf(M.FOREARMS, M.TRAPS),
        secondary = setOf(M.ABS, M.OBLIQUES, M.GLUTES),
        equipment = Eq.DUMBBELL,
        pattern = P.CARRY,
        isTimed = true,
        cue = "Tall and braced, short quick steps, do not let the shoulders slump.",
    ),
    Exercise(
        id = "DEAD_HANG",
        name = "Dead hang",
        primary = setOf(M.FOREARMS),
        secondary = setOf(M.LATS, M.SHOULDERS_FRONT),
        equipment = Eq.BODYWEIGHT,
        pattern = P.CARRY,
        isTimed = true,
        cue = "Relax into the hang, shoulders active at the end; grip work that costs nothing.",
    ),
)
