package com.myhealth.data.backup

import com.myhealth.data.db.dao.BackupDao
import com.myhealth.data.db.entity.ActivityLapEntity
import com.myhealth.data.db.entity.ActivitySessionEntity
import com.myhealth.data.db.entity.ActivitySourceRecordEntity
import com.myhealth.data.db.entity.ActivityStreamEntity
import com.myhealth.data.db.entity.BodyMeasurementEntity
import com.myhealth.data.db.entity.CalendarEventEntity
import com.myhealth.data.db.entity.CycleEntryEntity
import com.myhealth.data.db.entity.DailyHealthSummaryEntity
import com.myhealth.data.db.entity.DailyLoadEntity
import com.myhealth.data.db.entity.EventOverrideEntity
import com.myhealth.data.db.entity.GoalEntity
import com.myhealth.data.db.entity.ImportRecordEntity
import com.myhealth.data.db.entity.IngredientEntity
import com.myhealth.data.db.entity.MealLogEntity
import com.myhealth.data.db.entity.MealLogItemEntity
import com.myhealth.data.db.entity.MealTemplateEntity
import com.myhealth.data.db.entity.MealTemplateItemEntity
import com.myhealth.data.db.entity.NutritionTargetSnapshotEntity
import com.myhealth.data.db.entity.PlannedSessionEntity
import com.myhealth.data.db.entity.ProfileEntity
import com.myhealth.data.db.entity.RideBestEntity
import com.myhealth.data.db.entity.RunningBestEntity
import com.myhealth.data.db.entity.SleepSessionEntity
import com.myhealth.data.db.entity.ExerciseProgressEntity
import com.myhealth.data.db.entity.StrengthSetLogEntity
import com.myhealth.data.db.entity.StrengthWorkoutEntity
import com.myhealth.data.db.entity.StrengthWorkoutExerciseEntity
import com.myhealth.data.db.entity.SuggestedSessionEntity
import com.myhealth.data.db.entity.SuggestionBatchEntity
import com.myhealth.data.db.entity.SyncStateEntity
import com.myhealth.data.db.entity.TrainingPlanEntity
import com.myhealth.data.db.entity.WaterLogEntity

/**
 * In-memory [BackupDao] for the backup tests: one list per table, `REPLACE` semantics on the
 * primary key, and ids handed out from a single counter shared by every table — so a merge that
 * forgets to remap a foreign key points at the wrong row and the test notices.
 */
@Suppress("TooManyFunctions")
internal class FakeBackupDao : BackupDao {

    private var nextId: Long = 1L

    /** A table with an autogenerated `id`: `0` means "assign one", anything else is kept. */
    private fun <T> auto(list: MutableList<T>, rows: List<T>, id: (T) -> Long, withId: (T, Long) -> T) =
        rows.map { row ->
            val assigned = if (id(row) == 0L) nextId++ else id(row)
            list.removeAll { id(it) == assigned }
            list += withId(row, assigned)
            assigned
        }

    /** A table whose primary key is a natural value (a day, a key, the singleton profile id). */
    private fun <T, K> keyed(list: MutableList<T>, rows: List<T>, key: (T) -> K) = rows.map { row ->
        list.removeAll { key(it) == key(row) }
        list += row
        1L
    }

    val profile: MutableList<ProfileEntity> = mutableListOf()

    override suspend fun allProfile(): List<ProfileEntity> = profile.toList()

    override suspend fun insertProfile(rows: List<ProfileEntity>) = keyed(profile, rows) { it.id }

    override suspend fun deleteProfile() = profile.clear()

    val bodyMeasurement: MutableList<BodyMeasurementEntity> = mutableListOf()

    override suspend fun allBodyMeasurement(): List<BodyMeasurementEntity> = bodyMeasurement.toList()

    override suspend fun insertBodyMeasurement(rows: List<BodyMeasurementEntity>) =
        auto(bodyMeasurement, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteBodyMeasurement() = bodyMeasurement.clear()

    val activitySession: MutableList<ActivitySessionEntity> = mutableListOf()

    override suspend fun allActivitySession(): List<ActivitySessionEntity> = activitySession.toList()

    override suspend fun insertActivitySession(rows: List<ActivitySessionEntity>) =
        auto(activitySession, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteActivitySession() = activitySession.clear()

    val activitySourceRecord: MutableList<ActivitySourceRecordEntity> = mutableListOf()

    override suspend fun allActivitySourceRecord(): List<ActivitySourceRecordEntity> = activitySourceRecord.toList()

    override suspend fun insertActivitySourceRecord(rows: List<ActivitySourceRecordEntity>) =
        auto(activitySourceRecord, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteActivitySourceRecord() = activitySourceRecord.clear()

    val activityStream: MutableList<ActivityStreamEntity> = mutableListOf()

    override suspend fun allActivityStream(): List<ActivityStreamEntity> = activityStream.toList()

    override suspend fun insertActivityStream(rows: List<ActivityStreamEntity>) = keyed(activityStream, rows) { it.activityId }

    override suspend fun deleteActivityStream() = activityStream.clear()

    val activityLap: MutableList<ActivityLapEntity> = mutableListOf()

    override suspend fun allActivityLap(): List<ActivityLapEntity> = activityLap.toList()

    override suspend fun insertActivityLap(rows: List<ActivityLapEntity>) =
        auto(activityLap, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteActivityLap() = activityLap.clear()

    val dailyHealthSummary: MutableList<DailyHealthSummaryEntity> = mutableListOf()

    override suspend fun allDailyHealthSummary(): List<DailyHealthSummaryEntity> = dailyHealthSummary.toList()

    override suspend fun insertDailyHealthSummary(rows: List<DailyHealthSummaryEntity>) = keyed(dailyHealthSummary, rows) { it.day }

    override suspend fun deleteDailyHealthSummary() = dailyHealthSummary.clear()

    val sleepSession: MutableList<SleepSessionEntity> = mutableListOf()

    override suspend fun allSleepSession(): List<SleepSessionEntity> = sleepSession.toList()

    override suspend fun insertSleepSession(rows: List<SleepSessionEntity>) =
        auto(sleepSession, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteSleepSession() = sleepSession.clear()

    val syncState: MutableList<SyncStateEntity> = mutableListOf()

    override suspend fun allSyncState(): List<SyncStateEntity> = syncState.toList()

    override suspend fun insertSyncState(rows: List<SyncStateEntity>) = keyed(syncState, rows) { it.key }

    override suspend fun deleteSyncState() = syncState.clear()

    val calendarEvent: MutableList<CalendarEventEntity> = mutableListOf()

    override suspend fun allCalendarEvent(): List<CalendarEventEntity> = calendarEvent.toList()

    override suspend fun insertCalendarEvent(rows: List<CalendarEventEntity>) =
        auto(calendarEvent, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteCalendarEvent() = calendarEvent.clear()

    val eventOverride: MutableList<EventOverrideEntity> = mutableListOf()

    override suspend fun allEventOverride(): List<EventOverrideEntity> = eventOverride.toList()

    override suspend fun insertEventOverride(rows: List<EventOverrideEntity>) =
        auto(eventOverride, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteEventOverride() = eventOverride.clear()

    val trainingPlan: MutableList<TrainingPlanEntity> = mutableListOf()

    override suspend fun allTrainingPlan(): List<TrainingPlanEntity> = trainingPlan.toList()

    override suspend fun insertTrainingPlan(rows: List<TrainingPlanEntity>) =
        auto(trainingPlan, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteTrainingPlan() = trainingPlan.clear()

    val plannedSession: MutableList<PlannedSessionEntity> = mutableListOf()

    override suspend fun allPlannedSession(): List<PlannedSessionEntity> = plannedSession.toList()

    override suspend fun insertPlannedSession(rows: List<PlannedSessionEntity>) =
        auto(plannedSession, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deletePlannedSession() = plannedSession.clear()

    val suggestionBatch: MutableList<SuggestionBatchEntity> = mutableListOf()

    override suspend fun allSuggestionBatch(): List<SuggestionBatchEntity> = suggestionBatch.toList()

    override suspend fun insertSuggestionBatch(rows: List<SuggestionBatchEntity>) =
        auto(suggestionBatch, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteSuggestionBatch() = suggestionBatch.clear()

    val suggestedSession: MutableList<SuggestedSessionEntity> = mutableListOf()

    override suspend fun allSuggestedSession(): List<SuggestedSessionEntity> = suggestedSession.toList()

    override suspend fun insertSuggestedSession(rows: List<SuggestedSessionEntity>) =
        auto(suggestedSession, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteSuggestedSession() = suggestedSession.clear()

    val goal: MutableList<GoalEntity> = mutableListOf()

    override suspend fun allGoal(): List<GoalEntity> = goal.toList()

    override suspend fun insertGoal(rows: List<GoalEntity>) =
        auto(goal, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteGoal() = goal.clear()

    val ingredient: MutableList<IngredientEntity> = mutableListOf()

    override suspend fun allIngredient(): List<IngredientEntity> = ingredient.toList()

    override suspend fun insertIngredient(rows: List<IngredientEntity>) =
        auto(ingredient, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteIngredient() = ingredient.clear()

    val mealTemplate: MutableList<MealTemplateEntity> = mutableListOf()

    override suspend fun allMealTemplate(): List<MealTemplateEntity> = mealTemplate.toList()

    override suspend fun insertMealTemplate(rows: List<MealTemplateEntity>) =
        auto(mealTemplate, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteMealTemplate() = mealTemplate.clear()

    val mealTemplateItem: MutableList<MealTemplateItemEntity> = mutableListOf()

    override suspend fun allMealTemplateItem(): List<MealTemplateItemEntity> = mealTemplateItem.toList()

    override suspend fun insertMealTemplateItem(rows: List<MealTemplateItemEntity>) =
        auto(mealTemplateItem, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteMealTemplateItem() = mealTemplateItem.clear()

    val mealLog: MutableList<MealLogEntity> = mutableListOf()

    override suspend fun allMealLog(): List<MealLogEntity> = mealLog.toList()

    override suspend fun insertMealLog(rows: List<MealLogEntity>) =
        auto(mealLog, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteMealLog() = mealLog.clear()

    val mealLogItem: MutableList<MealLogItemEntity> = mutableListOf()

    override suspend fun allMealLogItem(): List<MealLogItemEntity> = mealLogItem.toList()

    override suspend fun insertMealLogItem(rows: List<MealLogItemEntity>) =
        auto(mealLogItem, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteMealLogItem() = mealLogItem.clear()

    val nutritionTargetSnapshot: MutableList<NutritionTargetSnapshotEntity> = mutableListOf()

    override suspend fun allNutritionTargetSnapshot(): List<NutritionTargetSnapshotEntity> = nutritionTargetSnapshot.toList()

    override suspend fun insertNutritionTargetSnapshot(rows: List<NutritionTargetSnapshotEntity>) = keyed(nutritionTargetSnapshot, rows) { it.day }

    override suspend fun deleteNutritionTargetSnapshot() = nutritionTargetSnapshot.clear()

    val waterLog: MutableList<WaterLogEntity> = mutableListOf()

    override suspend fun allWaterLog(): List<WaterLogEntity> = waterLog.toList()

    override suspend fun insertWaterLog(rows: List<WaterLogEntity>) =
        auto(waterLog, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteWaterLog() = waterLog.clear()

    val dailyLoad: MutableList<DailyLoadEntity> = mutableListOf()

    override suspend fun allDailyLoad(): List<DailyLoadEntity> = dailyLoad.toList()

    override suspend fun insertDailyLoad(rows: List<DailyLoadEntity>) = keyed(dailyLoad, rows) { it.day }

    override suspend fun deleteDailyLoad() = dailyLoad.clear()

    val runningBest: MutableList<RunningBestEntity> = mutableListOf()

    override suspend fun allRunningBest(): List<RunningBestEntity> = runningBest.toList()

    override suspend fun insertRunningBest(rows: List<RunningBestEntity>) =
        auto(runningBest, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteRunningBest() = runningBest.clear()

    val rideBest: MutableList<RideBestEntity> = mutableListOf()

    override suspend fun allRideBest(): List<RideBestEntity> = rideBest.toList()

    override suspend fun insertRideBest(rows: List<RideBestEntity>) =
        auto(rideBest, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteRideBest() = rideBest.clear()

    val importRecord: MutableList<ImportRecordEntity> = mutableListOf()

    override suspend fun allImportRecord(): List<ImportRecordEntity> = importRecord.toList()

    override suspend fun insertImportRecord(rows: List<ImportRecordEntity>) =
        auto(importRecord, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteImportRecord() = importRecord.clear()

    val cycleEntry: MutableList<CycleEntryEntity> = mutableListOf()

    override suspend fun allCycleEntry(): List<CycleEntryEntity> = cycleEntry.toList()

    override suspend fun insertCycleEntry(rows: List<CycleEntryEntity>) =
        auto(cycleEntry, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteCycleEntry() = cycleEntry.clear()

    val strengthWorkout: MutableList<StrengthWorkoutEntity> = mutableListOf()

    override suspend fun allStrengthWorkout(): List<StrengthWorkoutEntity> = strengthWorkout.toList()

    override suspend fun insertStrengthWorkout(rows: List<StrengthWorkoutEntity>) =
        auto(strengthWorkout, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteStrengthWorkout() = strengthWorkout.clear()

    val strengthWorkoutExercise: MutableList<StrengthWorkoutExerciseEntity> = mutableListOf()

    override suspend fun allStrengthWorkoutExercise(): List<StrengthWorkoutExerciseEntity> =
        strengthWorkoutExercise.toList()

    override suspend fun insertStrengthWorkoutExercise(rows: List<StrengthWorkoutExerciseEntity>) =
        auto(strengthWorkoutExercise, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteStrengthWorkoutExercise() = strengthWorkoutExercise.clear()

    val strengthSetLog: MutableList<StrengthSetLogEntity> = mutableListOf()

    override suspend fun allStrengthSetLog(): List<StrengthSetLogEntity> = strengthSetLog.toList()

    override suspend fun insertStrengthSetLog(rows: List<StrengthSetLogEntity>) =
        auto(strengthSetLog, rows, { it.id }) { row, id -> row.copy(id = id) }

    override suspend fun deleteStrengthSetLog() = strengthSetLog.clear()

    val exerciseProgress: MutableList<ExerciseProgressEntity> = mutableListOf()

    override suspend fun allExerciseProgress(): List<ExerciseProgressEntity> = exerciseProgress.toList()

    override suspend fun insertExerciseProgress(rows: List<ExerciseProgressEntity>) =
        keyed(exerciseProgress, rows) { it.exerciseId }

    override suspend fun deleteExerciseProgress() = exerciseProgress.clear()
}
