package com.myhealth.data.repository

import com.myhealth.data.db.dao.ActivityDao
import com.myhealth.data.db.dao.DayCount
import com.myhealth.data.db.dao.DayTrimp
import com.myhealth.data.db.entity.ActivityLapEntity
import com.myhealth.data.db.entity.ActivitySessionEntity
import com.myhealth.data.db.entity.ActivitySourceRecordEntity
import com.myhealth.data.db.entity.ActivityStreamEntity
import com.myhealth.data.db.relation.ActivityWithStream
import com.myhealth.domain.model.ActivitySource
import com.myhealth.domain.model.SportGroup
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

/**
 * In-memory [ActivityDao] for the ingestion tests (PLAN P2.5) — no Room, no Android. It models
 * the parts of the schema the ingestion pipeline relies on: autogenerated ids, the unique
 * `(source, externalId)` index of `activity_source_record`, and the `CASCADE` / `SET_NULL`
 * foreign keys that fire when a canonical row is deleted.
 */
class FakeActivityDao : ActivityDao {

    val activities = MutableStateFlow<Map<Long, ActivitySessionEntity>>(emptyMap())
    val sourceRecords = mutableListOf<ActivitySourceRecordEntity>()
    val streams = mutableMapOf<Long, ActivityStreamEntity>()
    val laps = mutableListOf<ActivityLapEntity>()

    private var nextActivityId = 1L
    private var nextRecordId = 1L
    private var nextLapId = 1L

    fun rows(): List<ActivitySessionEntity> = activities.value.values.sortedBy { it.startAtMillis }

    override suspend fun upsert(entity: ActivitySessionEntity): Long {
        val id = if (entity.id == 0L) nextActivityId++ else entity.id
        activities.value = activities.value + (id to entity.copy(id = id))
        return id
    }

    override suspend fun upsertAll(entities: List<ActivitySessionEntity>) {
        entities.forEach { upsert(it) }
    }

    override suspend fun getById(id: Long): ActivitySessionEntity? = activities.value[id]

    override suspend fun deleteById(id: Long) {
        activities.value = activities.value - id
        streams.remove(id)
        laps.removeAll { it.activityId == id }
        sourceRecords.replaceAll { if (it.activityId == id) it.copy(activityId = null) else it }
    }

    override fun observeRange(fromDay: Long, toDay: Long): Flow<List<ActivitySessionEntity>> =
        activities.map { all -> all.values.filter { it.day in fromDay..toDay }.sortedBy { it.startAtMillis } }

    override suspend fun getByBuckets(buckets: List<String>): List<ActivitySessionEntity> =
        activities.value.values.filter { it.dedupeBucket in buckets }

    override suspend fun getByDay(day: Long): List<ActivitySessionEntity> =
        activities.value.values.filter { it.day == day }.sortedBy { it.startAtMillis }

    override fun observeRecent(limit: Int): Flow<List<ActivitySessionEntity>> =
        activities.map { all -> all.values.sortedByDescending { it.startAtMillis }.take(limit) }

    override fun observeBySportGroup(
        group: SportGroup,
        fromDay: Long,
    ): Flow<List<ActivitySessionEntity>> = activities.map { all ->
        all.values.filter { it.sportGroup == group && it.day >= fromDay }
            .sortedByDescending { it.startAtMillis }
    }

    override suspend fun getFirstActivityDay(): Long? =
        activities.value.values.minOfOrNull { it.day }

    override fun sumTrimpPerDay(fromDay: Long, toDay: Long): Flow<List<DayTrimp>> =
        activities.map { all ->
            all.values.filter { it.day in fromDay..toDay && it.trimp != null }
                .groupBy { it.day }
                .map { (day, rows) -> DayTrimp(day, rows.sumOf { it.trimp ?: 0.0 }) }
                .sortedBy { it.day }
        }

    override suspend fun countPerDay(fromDay: Long, toDay: Long): List<DayCount> =
        activities.value.values.filter { it.day in fromDay..toDay }
            .groupBy { it.day }
            .map { (day, rows) -> DayCount(day, rows.size) }
            .sortedBy { it.day }

    override suspend fun getFullById(id: Long): ActivityWithStream? =
        activities.value[id]?.let { full(it) }

    override fun observeFullById(id: Long): Flow<ActivityWithStream?> =
        activities.map { all -> all[id]?.let { full(it) } }

    override suspend fun getRangeFull(fromDay: Long, toDay: Long): List<ActivityWithStream> =
        activities.value.values.filter { it.day in fromDay..toDay }
            .sortedBy { it.startAtMillis }
            .map { full(it) }

    override suspend fun upsertSourceRecord(entity: ActivitySourceRecordEntity): Long {
        val existing = sourceRecords.indexOfFirst {
            it.source == entity.source && it.externalId == entity.externalId
        }
        return if (existing >= 0) {
            val id = sourceRecords[existing].id
            sourceRecords[existing] = entity.copy(id = id)
            id
        } else {
            val id = nextRecordId++
            sourceRecords += entity.copy(id = id)
            id
        }
    }

    override suspend fun insertSourceRecordIgnoring(entity: ActivitySourceRecordEntity): Long {
        val clash = sourceRecords.any {
            it.source == entity.source && it.externalId == entity.externalId
        }
        if (clash) return -1L
        val id = nextRecordId++
        sourceRecords += entity.copy(id = id)
        return id
    }

    override suspend fun updateSourceRecord(
        source: ActivitySource,
        externalId: String,
        payloadJson: String,
        activityId: Long?,
        receivedAtMillis: Long,
        importRecordId: Long?,
    ) {
        val index = sourceRecords.indexOfFirst { it.source == source && it.externalId == externalId }
        if (index < 0) return
        sourceRecords[index] = sourceRecords[index].copy(
            activityId = activityId,
            payloadJson = payloadJson,
            receivedAtMillis = receivedAtMillis,
            importRecordId = importRecordId,
        )
    }

    override suspend fun deleteSourceRecord(source: ActivitySource, externalId: String) {
        sourceRecords.removeAll { it.source == source && it.externalId == externalId }
    }

    override suspend fun getSourceRecord(
        source: ActivitySource,
        externalId: String,
    ): ActivitySourceRecordEntity? =
        sourceRecords.firstOrNull { it.source == source && it.externalId == externalId }

    override suspend fun getSourceRecordsFor(activityId: Long): List<ActivitySourceRecordEntity> =
        sourceRecords.filter { it.activityId == activityId }

    override suspend fun getSourceRecordsOfImport(
        importRecordId: Long,
    ): List<ActivitySourceRecordEntity> =
        sourceRecords.filter { it.importRecordId == importRecordId }

    override suspend fun getUnstampedSourceRecordsInWindow(
        sources: List<ActivitySource>,
        fromMillis: Long,
        toMillis: Long,
    ): List<ActivitySourceRecordEntity> = sourceRecords.filter {
        it.source in sources && it.importRecordId == null && it.receivedAtMillis in fromMillis..toMillis
    }

    override suspend fun getAllUnstampedSourceRecords(
        sources: List<ActivitySource>,
    ): List<ActivitySourceRecordEntity> =
        sourceRecords.filter { it.source in sources && it.importRecordId == null }

    override suspend fun stampImportRecordId(id: Long, importRecordId: Long) {
        val index = sourceRecords.indexOfFirst { it.id == id }
        if (index < 0) return
        sourceRecords[index] = sourceRecords[index].copy(importRecordId = importRecordId)
    }

    override suspend fun upsertStream(entity: ActivityStreamEntity) {
        streams[entity.activityId] = entity
    }

    override suspend fun getStream(activityId: Long): ActivityStreamEntity? = streams[activityId]

    override suspend fun upsertLaps(entities: List<ActivityLapEntity>) {
        entities.forEach { lap ->
            laps += if (lap.id == 0L) lap.copy(id = nextLapId++) else lap
        }
    }

    override suspend fun getLaps(activityId: Long): List<ActivityLapEntity> =
        laps.filter { it.activityId == activityId }.sortedBy { it.lapIndex }

    override suspend fun deleteLaps(activityId: Long) {
        laps.removeAll { it.activityId == activityId }
    }

    private fun full(entity: ActivitySessionEntity) = ActivityWithStream(
        activity = entity,
        stream = streams[entity.id],
        laps = getLapsBlocking(entity.id),
    )

    private fun getLapsBlocking(activityId: Long) =
        laps.filter { it.activityId == activityId }.sortedBy { it.lapIndex }
}
