package com.myhealth.data.repository

import com.myhealth.data.db.dao.GoalDao
import com.myhealth.data.db.entity.GoalEntity
import com.myhealth.domain.model.GoalStatus
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

/**
 * In-memory [GoalDao] for [RoomGoalRepository]'s tests (PLAN P6.1) — no Room, no Android. Models
 * the autogenerated ids and the ordering the real queries promise, and nothing else.
 */
class FakeGoalDao : GoalDao {

    val rows = MutableStateFlow<Map<Long, GoalEntity>>(emptyMap())

    private var nextId = 1L

    override suspend fun upsert(entity: GoalEntity): Long {
        val id = if (entity.id == 0L) nextId++ else entity.id
        rows.value = rows.value + (id to entity.copy(id = id))
        return id
    }

    override suspend fun getById(id: Long): GoalEntity? = rows.value[id]

    override suspend fun deleteById(id: Long) {
        rows.value = rows.value - id
    }

    override fun observeByStatus(status: GoalStatus): Flow<List<GoalEntity>> = rows.map { all ->
        all.values.filter { it.status == status }
            .sortedWith(compareBy({ it.priority }, { it.targetDay ?: Long.MAX_VALUE }))
    }

    override fun observeAll(): Flow<List<GoalEntity>> = rows.map { all ->
        all.values.sortedWith(compareBy({ it.status.name }, { it.priority }))
    }

    override fun observePrimary(): Flow<GoalEntity?> = rows.map { all ->
        all.values.filter { it.status == GoalStatus.ACTIVE }.minByOrNull { it.priority }
    }

    override suspend fun updateStatus(id: Long, status: GoalStatus, updatedAtMillis: Long) {
        rows.value[id]?.let { row ->
            rows.value = rows.value + (id to row.copy(status = status, updatedAtMillis = updatedAtMillis))
        }
    }

    override suspend fun updatePriority(id: Long, priority: Int, updatedAtMillis: Long) {
        rows.value[id]?.let { row ->
            rows.value = rows.value + (id to row.copy(priority = priority, updatedAtMillis = updatedAtMillis))
        }
    }

    override suspend fun demoteOtherPrimaries(keepGoalId: Long, updatedAtMillis: Long) {
        rows.value = rows.value.mapValues { (id, row) ->
            if (id != keepGoalId && row.priority <= 1) {
                row.copy(priority = 2, updatedAtMillis = updatedAtMillis)
            } else {
                row
            }
        }
    }
}
