package com.myhealth.data.repository

import com.myhealth.data.db.dao.SuggestionDao
import com.myhealth.data.db.entity.SuggestedSessionEntity
import com.myhealth.data.db.entity.SuggestionBatchEntity
import com.myhealth.domain.model.SuggestionStatus
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

/**
 * In-memory [SuggestionDao] for [RoomSuggestionRepositoryTest] (PLAN P6.5) — no Room, no Android.
 * Models the autogenerated ids and the ordering the real queries promise; nothing more.
 */
internal class FakeSuggestionDao : SuggestionDao {

    val batches = MutableStateFlow<Map<Long, SuggestionBatchEntity>>(emptyMap())
    val sessions = MutableStateFlow<Map<Long, SuggestedSessionEntity>>(emptyMap())

    private var nextBatchId = 1L
    private var nextSessionId = 1L

    override suspend fun upsert(entity: SuggestionBatchEntity): Long {
        val id = if (entity.id == 0L) nextBatchId++ else entity.id
        batches.value = batches.value + (id to entity.copy(id = id))
        return id
    }

    override suspend fun getById(id: Long): SuggestionBatchEntity? = batches.value[id]

    override suspend fun deleteById(id: Long) {
        batches.value = batches.value - id
        sessions.value = sessions.value.filterValues { it.batchId != id }
    }

    override fun observeLatestBatch(): Flow<SuggestionBatchEntity?> =
        batches.map { rows -> rows.values.maxWithOrNull(LATEST_FIRST) }

    override suspend fun getByInputsHash(inputsHash: String): SuggestionBatchEntity? =
        batches.value.values.filter { it.inputsHash == inputsHash }.maxWithOrNull(LATEST_FIRST)

    override suspend fun updateBatchStatus(id: Long, status: SuggestionStatus) {
        val row = batches.value[id] ?: return
        batches.value = batches.value + (id to row.copy(status = status))
    }

    override suspend fun getLatestBatch(): SuggestionBatchEntity? =
        batches.value.values.maxWithOrNull(LATEST_FIRST)

    override suspend fun supersedeProposedBatches() {
        batches.value = batches.value.mapValues { (_, row) ->
            if (row.status == SuggestionStatus.PROPOSED) {
                row.copy(status = SuggestionStatus.SUPERSEDED)
            } else {
                row
            }
        }
    }

    override suspend fun upsertSessions(entities: List<SuggestedSessionEntity>) {
        entities.forEach { entity ->
            val id = if (entity.id == 0L) nextSessionId++ else entity.id
            sessions.value = sessions.value + (id to entity.copy(id = id))
        }
    }

    override fun observeSessionsForBatch(batchId: Long): Flow<List<SuggestedSessionEntity>> =
        sessions.map { rows -> rows.values.filter { it.batchId == batchId }.sortedBy { it.day } }

    override suspend fun getSessionById(id: Long): SuggestedSessionEntity? = sessions.value[id]

    override suspend fun getSessionsForBatch(batchId: Long): List<SuggestedSessionEntity> =
        sessions.value.values.filter { it.batchId == batchId }.sortedBy { it.day }

    override suspend fun getSessionsByIds(ids: List<Long>): List<SuggestedSessionEntity> =
        sessions.value.values.filter { it.id in ids }.sortedBy { it.day }

    override suspend fun updateSessionStatus(id: Long, status: SuggestionStatus) {
        val row = sessions.value[id] ?: return
        sessions.value = sessions.value + (id to row.copy(status = status))
    }

    override suspend fun updateSessionStatuses(ids: List<Long>, status: SuggestionStatus) {
        ids.forEach { updateSessionStatus(it, status) }
    }

    override suspend fun deleteSessionsForBatch(batchId: Long) {
        sessions.value = sessions.value.filterValues { it.batchId != batchId }
    }

    private companion object {
        /** Mirrors the DAO's `ORDER BY generatedAtMillis DESC, id DESC` tie-break. */
        val LATEST_FIRST: Comparator<SuggestionBatchEntity> =
            compareBy<SuggestionBatchEntity> { it.generatedAtMillis }.thenBy { it.id }
    }
}
