package com.myhealth.data.repository

import com.myhealth.data.db.dao.CycleDao
import com.myhealth.data.db.entity.CycleEntryEntity
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

/**
 * In-memory [CycleDao] for [RoomCycleRepository]'s tests (PLAN §5 P11.1) — no Room, no Android.
 *
 * It models the two things the real table guarantees: autogenerated ids, and the **unique**
 * `periodStartDay` index, which here throws exactly as SQLite would so a repository that forgets
 * to fold a duplicate start into the existing row fails the test instead of silently passing.
 */
class FakeCycleDao : CycleDao {

    val rows = MutableStateFlow<Map<Long, CycleEntryEntity>>(emptyMap())

    private var nextId = 1L

    private fun sorted(all: Map<Long, CycleEntryEntity>) = all.values.sortedBy { it.periodStartDay }

    override suspend fun upsert(entity: CycleEntryEntity): Long {
        val id = if (entity.id == 0L) nextId++ else entity.id
        val clash = rows.value.values.firstOrNull {
            it.periodStartDay == entity.periodStartDay && it.id != id
        }
        require(clash == null) { "UNIQUE constraint failed: cycle_entry.periodStartDay" }
        rows.value = rows.value + (id to entity.copy(id = id))
        return id
    }

    override fun observeAll(): Flow<List<CycleEntryEntity>> = rows.map { sorted(it) }

    override suspend fun getAll(): List<CycleEntryEntity> = sorted(rows.value)

    override suspend fun getById(id: Long): CycleEntryEntity? = rows.value[id]

    override suspend fun getByStartDay(periodStartDay: Long): CycleEntryEntity? =
        rows.value.values.firstOrNull { it.periodStartDay == periodStartDay }

    override suspend fun getLatest(): CycleEntryEntity? = sorted(rows.value).lastOrNull()

    override suspend fun deleteById(id: Long) {
        rows.value = rows.value - id
    }
}
