package com.myhealth.data.repository

import com.myhealth.data.db.dao.PlanDao
import com.myhealth.data.db.entity.PlannedSessionEntity
import com.myhealth.data.db.entity.TrainingPlanEntity
import com.myhealth.domain.model.PlanStatus
import com.myhealth.domain.model.PlannedStatus
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

/**
 * In-memory [PlanDao] for the plan-repository tests (PLAN P3.2) — no Room, no Android. Models the
 * autogenerated ids and the ordering the real queries promise; nothing else is needed here.
 */
class FakePlanDao : PlanDao {

    val plans = MutableStateFlow<Map<Long, TrainingPlanEntity>>(emptyMap())
    val sessions = MutableStateFlow<Map<Long, PlannedSessionEntity>>(emptyMap())

    private var nextPlanId = 1L
    private var nextSessionId = 1L

    override suspend fun upsert(entity: TrainingPlanEntity): Long {
        val id = if (entity.id == 0L) nextPlanId++ else entity.id
        plans.value = plans.value + (id to entity.copy(id = id))
        return id
    }

    override suspend fun getById(id: Long): TrainingPlanEntity? = plans.value[id]

    override suspend fun deleteById(id: Long) {
        plans.value = plans.value - id
        sessions.value = sessions.value.mapValues { (_, row) ->
            if (row.planId == id) row.copy(planId = null) else row
        }
    }

    override fun observeActivePlan(): Flow<TrainingPlanEntity?> = plans.map { rows ->
        rows.values.filter { it.status == PlanStatus.ACTIVE }.maxByOrNull { it.startDay }
    }

    override fun observeAllPlans(): Flow<List<TrainingPlanEntity>> =
        plans.map { rows -> rows.values.sortedByDescending { it.startDay } }

    override suspend fun archiveOtherActivePlans(keepPlanId: Long, updatedAtMillis: Long) {
        plans.value = plans.value.mapValues { (id, row) ->
            if (id != keepPlanId && row.status == PlanStatus.ACTIVE) {
                row.copy(status = PlanStatus.ARCHIVED, updatedAtMillis = updatedAtMillis)
            } else {
                row
            }
        }
    }

    override suspend fun upsertSession(entity: PlannedSessionEntity): Long {
        val id = if (entity.id == 0L) nextSessionId++ else entity.id
        sessions.value = sessions.value + (id to entity.copy(id = id))
        return id
    }

    override suspend fun upsertSessions(entities: List<PlannedSessionEntity>) {
        entities.forEach { upsertSession(it) }
    }

    override suspend fun getSessionById(id: Long): PlannedSessionEntity? = sessions.value[id]

    override suspend fun deleteSessionById(id: Long) {
        sessions.value = sessions.value - id
    }

    override suspend fun getSessionsByDay(day: Long): List<PlannedSessionEntity> =
        sessions.value.values.filter { it.day == day }.sortedBy { it.startMinuteOfDay }

    override suspend fun getSessionRange(fromDay: Long, toDay: Long): List<PlannedSessionEntity> =
        sessions.value.values.filter { it.day in fromDay..toDay }.sortedBy { it.day }

    override fun observeSessionRange(
        fromDay: Long,
        toDay: Long,
    ): Flow<List<PlannedSessionEntity>> = sessions.map { rows ->
        rows.values.filter { it.day in fromDay..toDay }.sortedBy { it.day }
    }

    override fun observeSessionsForPlan(planId: Long): Flow<List<PlannedSessionEntity>> =
        sessions.map { rows -> rows.values.filter { it.planId == planId }.sortedBy { it.day } }

    override suspend fun getReplaceableSessions(
        fromDay: Long,
        toDay: Long,
    ): List<PlannedSessionEntity> = sessions.value.values
        .filter { it.day in fromDay..toDay && !it.locked && it.status == PlannedStatus.PLANNED && it.sourceSuggestionId != null }
        .sortedBy { it.day }

    override suspend fun updateSessionStatus(
        id: Long,
        status: PlannedStatus,
        updatedAtMillis: Long,
    ) {
        val row = sessions.value[id] ?: return
        sessions.value = sessions.value +
            (id to row.copy(status = status, updatedAtMillis = updatedAtMillis))
    }
}
